# Generated by Django 2.0.5 on 2018-09-05 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('open', models.BooleanField(default=True)),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField()),
                ('seed', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField()),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerHomework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='DM/')),
                ('id_group', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('grade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('date_deposit_end', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deposit_number', models.IntegerField(null=True)),
                ('deposit_size', models.IntegerField(null=True)),
                ('id_requiredgroup', models.IntegerField(null=True)),
                ('answers', models.ManyToManyField(blank=True, to='playexo.AnswerHomework')),
                ('pldm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLDM')),
            ],
        ),
    ]
