# Generated by Django 2.0.5 on 2018-09-06 19:07

from django.db import migrations, models
import django.utils.timezone
import playexo.models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=playexo.models.user_directory_path)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField(null=True)),
                ('id_group', models.IntegerField(null=True)),
                ('id_homework', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerhomework',
            name='file',
        ),
        migrations.RemoveField(
            model_name='answerhomework',
            name='grade',
        ),
        migrations.AddField(
            model_name='homework',
            name='can_be_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerhomework',
            name='deposits',
            field=models.ManyToManyField(blank=True, to='playexo.Deposit'),
        ),
    ]
