# Generated by Django 2.0.5 on 2018-09-05 11:33

from django.db import migrations, models
import playexo.models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerhomework',
            name='file',
            field=models.FileField(upload_to=playexo.models.user_directory_path),
        ),
    ]
