# Generated by Django 2.0.5 on 2018-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0002_auto_20180906_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='extension',
            field=models.CharField(default='.pdf', max_length=100),
            preserve_default=False,
        ),
    ]
